### PR TITLE
PT-3844 Fix crash

### LINKED ISSUE #16: Crash with Zappr integration
Just had a crash when trying to create a repo due to the Zappr client:

```
➜ github-cli repo create my-repo-name                                                                                                                                                                        (kubeconfig is not found)
• Creating repository...   
• Adding labels to repository...
• Adding Zappr...          
• Adding teams to repository...
• Adding branch protections to repository...
• Repository created! 
 Here is how to access it git://github.com/hellofresh/my-repo-name.git
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1524bef]

goroutine 82 [running]:
github.com/hellofresh/github-cli/pkg/zappr.(*clientImpl).doRequest(0xc4201ca270, 0xc42011e000, 0x0, 0x0, 0x1, 0xc4205e43f0)
	/go/src/github.com/hellofresh/github-cli/pkg/zappr/client.go:147 +0x15f
github.com/hellofresh/github-cli/pkg/zappr.(*clientImpl).Enable(0xc4201ca270, 0xaeb3fdf, 0xc4201a49c0, 0x19a)
	/go/src/github.com/hellofresh/github-cli/pkg/zappr/client.go:83 +0x101
github.com/hellofresh/github-cli/cmd.RunCreateRepo.func2(0x8, 0x1772cb8)
	/go/src/github.com/hellofresh/github-cli/cmd/repo_create.go:159 +0x1e5
github.com/hellofresh/github-cli/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc42001dbc0, 0xc4205b41e0)
	/go/src/github.com/hellofresh/github-cli/vendor/golang.org/x/sync/errgroup/errgroup.go:58 +0x57
created by github.com/hellofresh/github-cli/vendor/golang.org/x/sync/errgroup.(*Group).Go
	/go/src/github.com/hellofresh/github-cli/vendor/golang.org/x/sync/errgroup/errgroup.go:55 +0x66
```

Also, integration with Zappr didn't happen. No webhooks and no branch protection rules.

### PR DESCRIPTION
**Pull request by startnow65**
Fixes #16

### CODE REVIEW

File: pkg/zappr/client.go [hunk 1]
```diff
@@ -144,6 +144,10 @@ func (c *clientImpl) doRequest(req *http.Request) (int, *zapprErrorResponse, err
 	zapprErrorResponse := &zapprErrorResponse{}
 	resp, err := c.slingClient.Do(req, nil, zapprErrorResponse)
 
+	if resp == nil {
+		return http.StatusInternalServerError, nil, errwrap.Wrap(ErrZapprServerError, err)
```
Comment (aleksandrzhiliaev) [inline pkg/zappr/client.go]: you assume that if you don't get any response it always internal server error code, maybe it should be a different code for those situations?

Comment (startnow65) [reply pkg/zappr/client.go]: I just picked that as an "i don't know the status" option, which one do you suggest ?

**Comment by aleksandrzhiliaev** [comment]
+1

Approved with Zappr  Approved with Zappr  Approved with Zappr  Approved with Zappr

**Review by aleksandrzhiliaev — APPROVED** [review]
